# Generated by Django 4.0.3 on 2022-04-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='coding.assignment'),
        ),
    ]
