# Generated by Django 4.0.3 on 2022-04-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_alter_class_assignments'),
        ('coding', '0002_assignment_active_alter_class_assignments_and_more'),
    ]

    operations = [
    ]
