# Generated by Django 4.0.3 on 2022-04-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_alter_class_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coding.assignment')),
                ('type', models.CharField(choices=[('R', 'Race')], max_length=1)),
            ],
            bases=('coding.assignment',),
        ),
        migrations.AddField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
