# Generated by Django 4.0.2 on 2022-03-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_teacher_learner_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secretKey', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('TAs', models.ManyToManyField(related_name='TAs', to='coding.Teacher')),
                ('students', models.ManyToManyField(to='coding.Learner')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.teacher')),
            ],
        ),
    ]
