# Generated by Django 4.0.3 on 2022-04-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_competitionprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionprogress',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitionprogress', to='coding.competition'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='coding.assignment'),
        ),
    ]
