# Generated by Django 4.0.2 on 2022-03-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('expectedOutput', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('practice', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.teacher')),
                ('solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.solution')),
                ('unitTests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.unittest')),
            ],
        ),
    ]
