# Generated by Django 4.0.3 on 2022-04-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_alter_competitionprogress_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionprogress',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='solution',
            field=models.TextField(default='', null=True),
        ),
    ]
