# Generated by Django 4.0.3 on 2022-04-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_merge_20220416_1424'),
        ('coding', '0005_remove_competitionprogress_percent_and_more'),
    ]

    operations = [
    ]
