# Generated by Django 4.0.2 on 2022-03-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('learner', models.ManyToManyField(to='coding.Learner')),
                ('question', models.ManyToManyField(to='coding.CodeQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('assignment', models.ManyToManyField(to='coding.Assignment')),
                ('learner', models.ManyToManyField(to='coding.Learner')),
            ],
        ),
    ]
