# Generated by Django 4.0.3 on 2022-04-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_class_competitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionWeightPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.codequestion')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(to='coding.questionweightpair'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='questions',
            field=models.ManyToManyField(to='coding.questionweightpair'),
        ),
    ]
