# Generated by Django 4.0.2 on 2022-03-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_status_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequestion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.teacher'),
        ),
        migrations.AlterField(
            model_name='codequestion',
            name='solutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.solution'),
        ),
        migrations.AlterField(
            model_name='codequestion',
            name='unitTests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.unittest'),
        ),
    ]
