# Generated by Django 4.0.3 on 2022-04-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_competition_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
