# Generated by Django 4.0.3 on 2022-04-18 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_questionweightpair_alter_assignment_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
