# Generated by Django 4.0.3 on 2022-04-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='status',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='status',
            name='question',
        ),
        migrations.DeleteModel(
            name='CompetitionProgress',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
