# Generated by Django 4.0.3 on 2022-03-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_remove_learner_user_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='unittest',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='codequestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unittest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unittest',
            name='input',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
