# Generated by Django 4.0.3 on 2022-03-15 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0010_solution_code_unittest_visible_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='progress',
            name='assignment',
        ),
        migrations.AddField(
            model_name='progress',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.assignment'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='progress',
            name='learner',
        ),
        migrations.AddField(
            model_name='progress',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='status',
            name='learner',
        ),
        migrations.AddField(
            model_name='status',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='status',
            name='question',
        ),
        migrations.AddField(
            model_name='status',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coding.codequestion'),
        ),
    ]
