# Generated by Django 4.0.3 on 2022-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_alter_class_tas_alter_class_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
