# Generated by Django 4.0.3 on 2022-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0013_codequestion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='secretKey',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
